# Generated by Django 3.2.16 on 2022-11-20 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0002_subscription_service'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscription',
            name='price',
            field=models.PositiveSmallIntegerField(blank=True, default=None, null=True),
        ),
    ]
