# Generated by Django 3.2.16 on 2022-12-03 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0003_subscription_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscription',
            name='comment',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
