# Generated by Django 3.2.16 on 2022-12-03 21:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0004_subscription_comment'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='subscription',
            index=models.Index(fields=['comment', 'price'], name='service_sub_comment_a43490_idx'),
        ),
    ]
